name: Test Azure Authentication

on: [push]

jobs:
  test-azure-auth:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login to Azure using Service Principal'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Run Azure CLI command'
      run: az account show
